[package]
name = "aircraft"
version = "0.8.0"
authors = ["Seiichi Horie<mail.example.com>"]
edition = "2021"
description = "Demonstration of shell-completion."

[dependencies]
clap = { version = "4.x", features = ["derive"] }
clap_complete = "4.x"