[package]
name = "aircraft"
version = "0.6.0"
authors = ["Seiichi Horie<mail@example.com>"]
edition = "2021"
description = "Demonstration of a switch argument."

[dependencies]
clap = { version = "4.*", features = ["derive"] }
