[package]
name = "aircraft"
version = "0.7.0"
authors = ["Seiichi Horie<mail.example.com>"]
edition = "2021"
description = "Demonstration of command/subcommand."

[dependencies]
clap = { version = "4.*", features = ["derive"] }
