[package]
name = "aircraft"
version = "0.2.0"
authors = ["Seiichi Horie<mail@example.com>"]
edition = "2021"
description = "Demonstration of the required arguments."

[dependencies]
clap = { version = "4.*", features = ["derive"] }
